posts = [
    u'Scholarship money got deposited! Wooh!',
    u"@Zach_3220 lol. that's what parents are for!you better get on it! Deadlines are going to be coming up soon!Need to get on scholarships too!",
    u"Got my scholarship! It won't pay for everything, but it helps!! God is good!!!",
    u'@ItsRiaah let me guess , you got your fafsa?',
    u'got 3 new scholarships ! Thank you Jesus \U0001f64f',
    u'Q&amp;A: How do I get grants &amp; scholarships 2 fund my education 2 B a Science teacher? http://t.co/DBkmD1t0 #educational #loans #student',
    u'Glad I got extra scholarship money. College will have you broke!!!',
    u'God is SO good! Got the Wells Fargo Scholarship I applied for! \U0001f606\U0001f606\U0001f606',
    u'Got my scholarship back!:D',
    u'Had the perfect morning. Got the scholarship. Paycheck came in a day early. God is good.',
    u"Just applied to 14 scholarships. Let's hope for at least one to go through! #poorstudent",
    u'Some serious talks with Ms. Boyes today about scholarship opportunities.....',
    u"I've said this before..\nScrew Fafsa!! I always seem to have problems with it",
    u'I really wanna get a scholarship now.',
    u'College visits &gt;&gt;&gt;&gt;',
    u'How does my mom not trust me going on a college visit without her when ill be at college without her next year..',
    u"I got accepted to college, guys. GUYS. UNIVERSITY OF NORTHERN IOWA. I'M GOING.",
    u'Restarting this college shit #FAFSA',
    u"http://t.co/hBAKD5ag\nI officially hate college visits cuz I'm gonna miss meeting Vic that weekend. :( #VeryUpset",
    u'I really wanna study abroad this summer. I need to look into that again and some more scholarships',
    u'Thanks guys. How do I go about this student loan without being a student,anyone know ?',
    u'I need someone to go on this college visit with me',
    u'God is so good! i got the scholarship to go to #PASSION2013 :D',
    u'i cant wait to go on this college tour .. gonnah be so funnnnnnnn',
    u'Who should i consolidate student loans with http://t.co/4KmRGfwB',
    u'I got the scholarship to Passion! Headed to the dome :)',
    u"@all_smiles10 Lol that's good I miss y'all So mad I still haven't met her yet. &amp; I just got out of class. Looking for scholarships right now",
    u"Second stop on the #Nomadness Travel Tribe College Tour tonight... Manhattan College you're up next.",
    u'My college tour guy was soo cutee !! ^.^',
    u'People ask the STUPIDEST questions on college tours.',
    u'i need all the scholarships i can get',
    u'College visits are so stressful. Someone just pick for me!',
    u'Dont know weather to go back to college or not? #decisions',
    u"College visit tomorrow so glad I'm not going to school #needabreak",
    u'APT tomorrow, and College visits Friday? #NoMoreSchoolThisWeek',
    u"Why am I the only one that hasn't started the college application process \U0001f610",
    u"3 college tours scheduled... \U0001f633 can't believe this!",
    u'I just realized that next month my student loan payments will be rolling in. Has it really been 6 months? Yikes.',
    u'My day at school was sucky but it got better. God is so amazing to me, He led me to finding those scholarships that turned my day around. &lt;3',
    u'Hey, does anybody want to decide what I should do with my life? Just took 3 college major quizzes and got all different results..',
    u'one of many college tours! it was amazing. definitely applying #Devry http://t.co/51yF1VZr',
    u'I wanna go on college visits.',
    u'Woooohooo got a scholarship o yeah',
    u'To take out a student loan or not? Im not old enough for this decision!! #wahhhh',
    u'Applied to UAB yesterday. I hope I get a big enough scholarship to go.',
    u'college tour coming fast !',
    u'actually went on college visits...I feel so accomplished.',
    u'Can somebody please tell me how the fuck to get a student loan...',
    u'I only went to one college visit and I already want togo to college. this is bad',
    u'Need to set up some college visits! #ASAP',
    u'College tour, say what?',
    u'I need a scholarship.. :( BADLY!',
    u'I want a scholarship cause I had to grow up in Kc',
    u"24 ACT to go on a college visit? Yeah. No I don't have that. I'm still going on a college visit. Sorry Central.",
    u'Can somebody near a farm confirm that pigs are still earth-bound? Because I just had a pleasant conversation with my student loan company.',
    u'I wish I could go to choir everyday, I need that scholarship money... But I be busy',
    u"I wish school was only 3 days a week. Can't wait for college D:",
    u'The college tour was GREAT! :D',
    u"Had my first college visit today.. Don't feel old enough for this shit yet.",
    u"can't wait for college omg",
    u'Fafsa why must you suck SOOOOOOOO bad. #BOOYouWhore',
    u'I Need Some Scholarships',
    u"At this scholarship dinner. I thank God for blessing me to be able to go to school for free. Idk what I'd be doing otherwise.",
    u'Hungry. No time. Gotta get ready for these college visits.......still so hungry.',
    u'First acceptance letter! #college',
    u'that college visit was so amazing. i cant waiy to grow up &amp;&amp; be ok my owwwn',
    u'Just planned my first college visit #betterlatethennever',
    u'$750 scholarship!! Drinks on me this weekend',
    u'Got into college! #mizzou #gotigers',
    u"I'm not worried about getting accepted into colleges. I'm worried about the scholarships that I need",
    u'Updating my resume. I need scholarship !! #COTACyT',
    u'RMC this weekend for sure!!! :)let the college search begin  #excited',
    u'Oh Em Geeeee another scholarship!!! God is good! 2012 has just been great! Yaaaaaay!!! Made this horrible week so much better!! #blessed',
    u'I wanna go on a black college tour!',
    u'Just got accepted to Northwest and got my first scholarship!',
    u'All I want is a scholarship',
    u'I am so proud of my self for getting stuff done and taking the initiative! I just need to apply for more scholarships.',
    u'I just want to go on a college visit to UCLA',
    u'..i think i wanna go back to college ....just cuz im ready now -before i felt like i HAD to.',
    u'Hmm what would i wear to a college visit?',
    u'I need to go on some college tours.',
    u'I need some scholarships !!!',
    u"I can't wait for college I want out of here",
    u"I'm so excited for life! I've never been this excited! I can't wait for college! \U0001f60a",
    u'I need to start some more College Visit.',
    u'Need to get some scholarships. #rt',
    u'I need to look for some scholarships!',
    u'Is it January yet? cause this girl is ready to start the new year off right at passion! So excited I got the scholarship to go #blessed \U0001f60a',
    u'this college visit is making me so excited for next year! it needs to hurrryyyy #ilovecollege',
    u"Can't wait for college !! #OU",
    u'I need a new scholarship.',
    u'Just got into college &amp; its only me &amp; kat great :/',
    u'I need a scholarship \u2639\u2639\u2639',
    u'I Wanna Go On A College Tour',
    u"College visit today andddd it's game day! #gonnahaveagoodday \u263a\U0001f44d",
    u'#bajet2013 i want scholarship.',
    u'i want to go on some college tours soon, but i need someone to take me.',
    u'So, how do I start applying for scholarships...',
    u'I gotta look up more scholarships today \U0001f612',
    u"It's raining \u2601\u2614... That must mean it is time for a college tour \U0001f393",
    u"Don't understand how a student loan can do nothing but increase in two years? \U0001f636",
    u'Well i wish i looked cuter for this college tour.. #ohhey',
    u"This college visit is ass. I'm boreddd",
    u'College visits are boring \U0001f44e',
    u'Need to find some scholarships',
    u'We are really over dressed for this college visit..',
    u'applying for scholarships and shit because bad bitches go to college.',
    u'College tour at ridge, #boring. Someone text me please, thanks.',
    u'Went to 2 college visits today already',
    u'Headed up to #MTSU for my college visit.',
    u'Driving to UW Madison with my mommy for a college visit today =) #noschool #college',
    u'This FAFSA shit is too freaking long',
    u"I wish I could win a Scholarship :')",
    u'Oh man the nervous part of this college visit just set in #goaway',
    u"Seriously can't wait for college.",
    u"Yes, I haven't got into college. I haven't got any offer from any college yet. But that doesn't mean I'm that fucking stupid lah, fucktard.",
    u'this college visit &gt;&gt;',
    u'i need to make some more college visits',
    u'Went to fill out my #FAFSA only to realize I had already filled it out!',
    u'Good luck - was on a college tour and stopped by your current digs, but you had just closed up.',
    u'I wanna go on a college visit .',
    u'whoever feels like wasting money like kim k did, please remember me. i need scholarship',
    u'college visit is finally set up. #wednesdayyyyyyyyy :)',
    u'I need to go on college visits gahhhh',
    u"Can't wait for college. #Parties #Boys #Freedom #Parties",
    u'college visits just make me want to go to college more! #cantwait',
    u'College visits are so stressful \U0001f625',
    u"I'm taking AVID instead because I need scholarships.",
    u"Can't wait for college #getmeoutahere",
    u"I can't wait for college. #ComeFaster",
    u"Dude- #UIndy is awesome! I can't wait for college!!",
    u'These college tours are not making things easy...',
    u'My dads trying to get me to ditch this college visit smfh',
    u'Mom decided she could lead our college  tour. First door we went through sounded the alarm through the whole building. #genetics #calmity',
    u"Can't wait for college!!",
    u'And now I begin my college search.',
    u"Just got a scholarship!!!! \u263a\u263a\u263a lol and I didn't even do anything...not gona complain its free money!!!!",
    u'I got one of my scholarships back ^_^ #ThankGod',
    u'Got accepted and a scholarship!',
    u'Yeah... I got the scholarships bitch',
    u'I got one of my scholarships back for Spring already #GodIsGood',
    u'Damn it feels good to know I got into college somewhere!',
    u'The college tour was better when I was punch :-/',
    u"Can't wait for college!",
    u'Scholarship banquet 1 done. Met most of the donors and got to speak on a student panel. Beyond thankful for the opportunity !',
    u'First college tour. #success',
    u'Got my first scholarship(:',
    u'I Could Easy Get A Scholarship In Theater Arts Tf!',
    u'been looking for scholarships all morning. let me try to get soem homework finished though.',
    u"i can't wait for college !",
    u'really good college visit today :) #excited',
    u'This scholarship just makes it even better',
    u'Why does the fafsa have to be written in like a whole other language? #collegekidprobs',
    u'ready for this college tour next month. #ArmstrongAltantic',
    u'Best college visit ever! #Lovemetro! @mikalahavlovic!',
    u'College visit next friday so 3 days of school too',
    u"The new Kesha song makes me wanna party. Can't wait for college. #HaterMentality",
    u'I need to look for scholarships O_O',
    u'I got a scholarship ! #HardWorkPaysOff',
    u'Looking for scholarships and grants is much harder then I thought.. Smh ughh',
    u"Everyone is saying that they got into college... And i still haven't applied... To any... #awk",
    u"I can't wait for college #getmeoutofhere",
    u'So excited for all these college tours this week. Yayayay, so close.',
    u"Since I have no plans this weekend, I'll need to keep the laptop so I starts fafsa and watch that damn accuplacer video for school",
    u'Got my first acceptance letter today! #yay #college',
    u'Yay!  I got the scholarship',
    u'the reasons WHY i stress is: 1. im a SENIOR in HS 2. im LOOKING for COLLEGES 3. i NEED scholarships 4. my MOMMA witch is the BIG one &lt;----',
    u"I need to find some scholarships while I'm off",
    u"I'm very happy with my life right now. Can't wait for college",
    u'Excited for this college visit',
    u"oh man can't wait for college. \n\nparents suck ass. \U0001f621\U0001f44a",
    u'I got 3 scholarships today....Tonight its #TTU',
    u'This weekend is dedicated to scholarships and applications. Lets go.',
    u'I feel soo relieved. Hopefully I get more scholarships',
    u"Yay, I got a scholarship :')",
    u'College tours all day and its raining.....smh.',
    u'I think my acceptance letter calls for a celebration this weeekeend ;) #ayee',
    u"Can't wait for college",
    u'$1500 scholarship #blessed',
    u'Actually got a scholarship #&lt;3',
    u'best college tour ever! #inlove',
    u'It may have taken 9 college visits, but i think i found one i like. #yes',
    u'Brianna reminded me i still need to apply for scholarships too',
    u"Got the college scholarship so yeah, THAT'S AWESOME. hey money, not seen much of you in a while.",
    u'#plottwist we are actually going to Babson for a college tour',
    u'got 5 scholarships done so far ^_^',
    u'I wish I knew exactly what career I want to get into ... It will make this college and scholarship search much easier \U0001f614 #frustrated',
    u'I WILL live it up when college applications, SATs, and scholarships are done. #Notnow',
    u"people are getting accepted to college and i'm sitting here having not applied yet #whoops",
    u'My college visit was sweet! I really like that college',
    u"Truthfully I just want to get a scholarship! So my mom doesn't have to pay my way to college, and I wont have to pay em back!",
    u'Determined to finish my application to UK and fafsa stuff THIS weekend!',
    u'college visit went well :) now to spend the weekend at isu with cody! :)',
    u'Just submitted my last college application. #meow #nervous'
    ]
