posts = [
    u'SERIOUS INQUIRIES ONLY! For those that need scholarships for tuition payments. http://t.co/3m80T7AR via @winscholarships',
    u'UT needs to hurry and give me my scholarship moneyzzzz! I got things I need to get! \U0001f4b5\U0001f4b0\U0001f4b0\U0001f4b0',
    u"Congrats to our 5 Commended students in the Nat'l Merit Scholarship Program. We are so proud of you. http://t.co/Z2PTTA9Z",
    u'yay for more scholarship money. If only i was brown and went to school for free #whitepeopleproblems',
    u'@CHSBlackKnights SunTrust Off To College Scholarship Sweepstakes not based on need or GPA. Visit http://t.co/fXmYKJRf for your chance to win',
    u"i don't even know if i got my fafsa paid in yet.. i guess so.",
    u'I need my scholarships to get up there',
    u'Application deadline is Oct. 15. This is such an important scholarship for those who need it. Please pass the word! NB  http://t.co/XSugLD4v',
    u'@btoney12 did u ever get your scholarship checks from english yet?',
    u'@PatrickYeates ahh cool, I had a day off today (: back to college tomorrow though ):',
    u'Kauai Board of Realtors hosting youth scholarships fund raiser with Las Vegas style fun Sat night http://t.co/NtP9Wbut',
    u'Is this our future? RT @carllygo: "Student loan debt in the US hits $1 trillion" reports CNN',
    u'Another reason not to have kids - College Tuition.  4 years of *In-State* tuition at #UGA is over $77,000. Up $50,000 from 12 years ago.',
    u'Kauai Board of Realtors hosting youth scholarships fund raiser with Las Vegas style fun Sat night http://t.co/1gXDzfo7',
    u"@ThePrincipal will be speaking at this week's meeting in CBB 225. Join us for a chance to win a $500 scholarship. #ThePrincipal",
    u'Nearly 4,000 students awarded Whitney M. Young Scholarships so far. Your ticket to the #NYULClassic does great things!',
    u'Reply To: How to find Financial Aid for online college http://t.co/FLbrhlcF ##scholarships',
    u'Reply To: How to find Financial Aid for online college http://t.co/CQkzX35n ##scholarships',
    u'"@PHABMK6: School pictures are the biggest scam in America." Class Rings, College tuition, Hospital bills, Printer Ink, Theatre food',
    u'@EvanM396 and she got into college how?.....',
    u'The Student Loan Interest Tax Deduction: Are You Taking Advantage of It? - http://t.co/x5VgsQMT',
    u'Calling community college students: How is your school helping you achieve your dreams? We have a $1,500 scholarship! http://t.co/keUgCaH6',
    u'Great meeting today with Boys &amp; Girls Clubs to discuss the future of the Steve Francis Foundation Scholarships. Youth are our Future!',
    u'Join http://t.co/fWJxfVn6 and we could both win a scholarship! http://t.co/YcLHeBny via @winscholarships',
    u'Work with college presidents to keep college tuition down!!!',
    u"There's still time to apply for an NCSS Conference scholarship! Deadline is 9/28. http://t.co/5a8DAlj5  #sschat #ncss12",
    u'What Is a Cosigner On a Student Loan?: When a college student is attempting to get a student loan, one main factor... http://t.co/QXzq3fhD',
    u'@USCBAA has provided over 2 million dollars in scholarships to over 2K undergraduate, graduate and professional students. #fact',
    u"@LaurenNicole93 right I've decided I deffo need to come out soon! Next week? When I get my student loan? :)",
    u'This is a great program. And the scholarship is a great way to participate! http://t.co/0BRji3Ej',
    u"High school is shit. I can't wait for college",
    u"@AshleyJudd92 told the bank I'm a student..still no student loan. What the fuck is that about? You'd swear you have to be a student.",
    u'Where To Begin When Saving For College?  Talk To Me! http://t.co/u6nJz8gQ',
    u"Bitch, how the fcuk you independent and you're buying handbags with student loan money?",
    u"Can't wait for college.  http://t.co/reMJe81P",
    u"Can't wait for college!",
    u'ScholarshipPoints: Join, earn points, enter #scholarships, pay for #college! http://t.co/V4GEfrJz',
    u'\u201cOriginality is the essence of true scholarship. Creativity is the soul of the true scholar.\u201d http://t.co/BkL5QaCI',
    u'More scholarships! http://t.co/0dusvveu',
    u'Photo: More scholarships! View Post shared via http://t.co/eKoYuDvh http://t.co/gnfLvbsu',
    u'Who Graduates College with Six-Figure Student Loan #Debt? August 2012 report http://t.co/5wUCrpCE #education #studentdebt',
    u'WELL I HAD TO. \u201c@BarackObama: "No family should have to set aside an acceptance letter to a college because they don\u2019t have the money."\u201d',
    u'@josh_clarke91 you going back to college this year or wa?',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/6O0BfI63',
    u'Start work experience tomorrow, seeing my clarke on friday, going cinema on saturday, seeing a friend on sunday. Then back to college.',
    u'I love that football took all the scholarships. #shitnoABstudentsays @ABstudentsWV',
    u"USF didn't offer a scholarship to a single BSU player (including the one from tampa with the game winning INT), yet BSU still won",
    u"Fuck Sallie Mae and everyone that works there, bet me I won't burn it down, 14% interest student loan? Helping students in need..... Fuckoff",
    u'Turned down for a college loan? If you have good credit, a PLUS loan might be available. CBS News: http://t.co/qWbjM1dT',
    u"Omg I hate school so fucking much. Can't wait for college.",
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/5TPJDDtp',
    u'I heard KG is doing a #KayGeeLiveCuts College Tour.. Shit come to UT. Lol I gotta alot of niggas in need of a haircut.',
    u'Striking Rise in Six-Figure Student Loan Debt: In "Who Graduates College with Six-Figure Student Loan Debt?," a ... http://t.co/q3B0bjcU',
    u"When i'm feeling sorry for myself I online shop. Student loan where you at?",
    u'Join http://t.co/aPiHx8fi and we could both win a scholarship! http://t.co/RdgeiVFa via @winscholarships',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/OZNVgzvA',
    u'High school students: Write a haiku about Cable TV, win a $1000 college scholarship http://t.co/QP7EQH4r',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/pO1Ye7Z8',
    u'Which to pay off first: car payment or student loan? http://t.co/xEjVU2oa',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/pXJS9ht9',
    u'FREE College Tuition? They\u2019re on @PLNDR! Enter to Win 10K now http://t.co/M0cPc2Rd',
    u'She juss move outtah momma and juss went back to college she is my dancer &amp; when she dance i throw her dollars',
    u'Today is beyond THE WORST. I just want my fuckin scholarship!',
    u"How much information can a student loan centre find out from a SIN? - Can they find out if/where I'm working and the... http://t.co/tGUvWimi",
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/12qOdU2S',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/0uKO7yHG',
    u'Check out CollegeXpress! This is an awesome resource for Scholarships and Colleges. -  http://t.co/lCvxSDUc',
    u'Check out CollegeXpress! This is an awesome resource for Scholarships and Colleges.  -  http://t.co/7GpxvVnW',
    u'just made a wish list on nasty gal for when my student loan comes through #dangerous',
    u'WAS TALKIN TO THE MEN THAT ACCEPTED ALL BASKETBALL SCHOLARSHIP IN HE WANT TO PLAY BALL WITH ME TODAY',
    u'Reply To: How to find Financial Aid for online college http://t.co/CXc1dHFu ##scholarships',
    u"this government are taking the piss man where's my student loan at?????/",
    u'Not tryna go to sat class for 3 hours tonight',
    u'Wish my scholarship included ah presidential suite',
    u'CLICK THE LINK ITS NOT SPAM. then exit the window for all i care. get me points for scholarships!\nhttp://t.co/ZUuqy1TY via @winscholarships',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/8RzmUDz1',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/fwdCc4qC',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/nUeJbWUh',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/AqvBJvyg',
    u"Where's my student loan? :(",
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/roTUk9kl',
    u'Biden Lies About Romney\u2019s Student Aid Plans http://t.co/LCw9rggd #tcot',
    u'@BenjaminS_Nufc0 hi jake interested in a soccer scholarship? If so MSG bak asap Check r website http://t.co/sQmJgFz8 #TrainHardStudyHarder',
    u"The History of Scrollbars @MrRandyWATTsun lmao I'm not paying for college for none of my children! No sir. http://t.co/apjAdVQD",
    u'Join http://t.co/YxddOCx5 and we could both win a scholarship! http://t.co/zE5Rxkoh via @winscholarships',
    u'@4liakcadag2 hi ali interested in a soccer scholarship? If so MSG bak asap Check r website http://t.co/sQmJgFz8 #TrainHardStudyHarder',
    u'\u201c@BarackObama:No family should have to set aside an acceptance letter to a college like Bowling Green because they don\u2019t have the money."\u201d',
    u'@newsoncharlie hi charles interested in a soccer scholarship? If so MSG bak asap Check r website http://t.co/sQmJgFz8 #TrainHardStudyHarder',
    u"Bynum @MrRandyWATTsun lmao I'm not paying for college for none of my children! No sir. http://t.co/TvSH1xD9",
    u'@TheSamMuir hi sam interested in a soccer scholarship? If so MSG bak asap Check r website http://t.co/sQmJgFz8 #TrainHardStudyHarder',
    u'@leahfootball hi leah interested in a soccer scholarship? If so MSG bak asap Check r website http://t.co/sQmJgFz8 #TrainHardStudyHarder',
    u"You know she just moved out of momma's just went back to college She is my dancer when she dance I throw her dollars",
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/hAgo9Ci3',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/4O9INXQB',
    u'Senate Dems: Senator Sullivan on the end of the Legislative Scholarship Program http://t.co/8jzh2rae',
    u'Join http://t.co/NTJPxaos and we could both win a scholarship! http://t.co/dmbiipsA via @winscholarships',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/xGRA71eD',
    u'Prepare For the Future - Get the Best #Education You Can! http://t.co/lckfKGhr #udemy #course #college #school #students #scholarships',
    u'Join http://t.co/H6KS87xv and we could both win a scholarship! http://t.co/2vhUBO83 via @winscholarships',
    u'Reply To: How to find Financial Aid for online college http://t.co/8Nx6ZHLV ##scholarships',
    u'Yu  kno she just move out mommas.,  just went back to college., she is my dancer, when she dance I throw her dollars.',
    u'"@jordmac3: "I once turned a whole student loan into vodka. Your move Jesus." @sam_thomas9  #thatsus #oops"',
    u'Reply To: How to find Financial Aid for online college http://t.co/NIB5zMik ##scholarships',
    u'We would like to invite all Lincoln High School Seniors to apply for the Taylor Moseley Scholarship. \n\nPlease... http://t.co/rhnjC1b6',
    u'Boss scholarship yh RT @MsFola_: We no dey pay school feees :D RT @tennerick: Yeap "@Dahmolah: Did u eva owe school fees in secondary skul?"',
    u"I got an email about a birthday scholarship. The only requirement is that you have to have been born... I'm totally entering!",
    u'Who wants to go to a Gala??? http://t.co/1SdS1QuG\n\n*Funds raised at the Annual Gala underwrite program scholarships for Girls on the Run -\u2026',
    u'What is the best student loan to take out? http://t.co/tlgwCI7Q',
    u'@Becky_Hicks Jesus! You could buy a new car each year for that! (Mind getting me a Golf? :L)  Does the student loan not cover it?',
    u'Anyone wanna buy me this? :P oh the temptations of student loan... http://t.co/Wawg41X9',
    u'Courageous Persuaders 2013 Video Contest. Prize: $3000 scholarship! Make a PSA about the dangers of underage drinking. http://t.co/Lv3lYeUZ',
    u'\u201c@ashleyosteen1: Thanks soooo much to @BethMooreLPM for the scholarship to #passion2013 #beyondexcited!!\u201d//sooooo excited for you',
    u'@SilllyBillyy do you plan to take out a student loan for college?',
    u'Join http://t.co/h0Vjpf5C and we could both win a scholarship! http://t.co/HtlkTARp via @winscholarships',
    u'Join http://t.co/k5DFnrjs and we could both win a scholarship! http://t.co/XDz2k02Z via @winscholarships',
    u'Join http://t.co/x92BU75k and we could both win a scholarship! http://t.co/rYARpIxT via @winscholarships',
    u'@amrshaker543 No.. wish i were actually.. but cldnt afford it and didnt get a scholarship. got my scholarship at GUC..',
    u'Join http://t.co/DATRB6S4 and we could both win a scholarship! http://t.co/zgZlNOBL via @winscholarships',
    u'Join http://t.co/USi6Z2dm and we could both win a scholarship! http://t.co/hbVxzG4J via @winscholarships',
    u'New post: How do scholarships and student loan http://t.co/0dWevHV0',
    u'RT @BTraymartin9: The TMfoundation will focus on S.A.M.E. ( scholarships advocacy mentoring (cont) http://t.co/ashTWpMO',
    u'RT @damonism: Parliamentary Library Summer Research Scholarship \u2013 looks like a great opportunity for wonky postgrads http://t.co/TdipLL02',
    u'RT @mefatweets: This is a good trend. "Student Loan Debt Draws More Attention at Colleges:" http://t.co/wyde58jV @USNewsEducation',
    u'College Tuition? Start Up Costs? They\u2019re on @@PLNDR! Enter to Win 10K now http://t.co/3Cr1vT1T',
    u'How Much is Student Loan Debt Costing You? (infographic) http://t.co/RG0TFtAA',
    u'How many Penn State football scholarships are now only being used for a student to go to school for free and not having to play football?',
    u'"@OccupyChicago: Between 1990 and 2011 college tuition fees have risen 300% and health care costs have risen 150%."',
    u'#Student loan consolidation: What do the numbers mean? Please share. http://t.co/WUbKO063',
    u'Join http://t.co/97qGUvwp and we could both win a scholarship! http://t.co/jyj52SrV via @winscholarships',
    u"@leahlouisecarr why? And what's ed??? Only because of student loan!!!!!",
    u'Too many new Paleo books and no $ to buy them. U think a student loan would cover cookbooks?@PrimalPalate @balancedbites @everydaypaleo',
    u'What Is a Cosigner On a Student Loan? http://t.co/T2c8mxHL',
    u'How cn I get a student loan if I alrdy have a pell grant? http://t.co/5yDzk18d #educational #loans #student',
    u'Can I take out a student loan to buy a motorcycle?: http://t.co/arlK1La6',
    u'What Exactly is Alternative Student Loan Consolidation? http://t.co/ZVgMyGEo',
    u'@BenChild1994 when do you get ur student loan? that dress is calling my name!!! :-( hahaha',
    u'How to Consolidate Private Student Loan Consolidation? http://t.co/8ygnw4Kf',
    u"Also, student loan just came through and that is what it's there for... Right?",
    u'Have anyone of you got your student loan in yet?',
    u"HOW IS EVERYONE'S STUDENT LOAN IN BUT MINE?!",
    u"Oh, hello Slipknot at Download 2013. What's that, student loan comes in next Thursday? Tickets ahoy!",
    u'@SpiderShan246 daym!! U mean your student loan? No lol Manchester :) 4 dates in the uk though?! Whattttt?!',
    u'Student Loan:\n\n"A mystical transaction in which a student and/or parent subjects themselves to financial slavery... http://t.co/G9mKz2yi',
    u'Student loan, where art thou?',
    u"@JackWills does this offer apply online? My student loan goes in on the 4th and don't have a JW near me! :/",
    u'I hate this 3 hour break I have. I cba to go back to college at 3.30 ;(',
    u"That exam just had its way with me, and I don't even care. That full scholarship was nice while it lasted. #SeeYaLater #ProbablyNot #Bye",
    u"@thekidam how did u get that? Like student loan or what's",
    u'Seriously? No student loan is paid off check? No tickets to a game? Just an email with purple and orange bal http://t.co/LM0O71QE',
    u"Wow, just got the most amazing scholarship to give away to attend @NutritionSchool. Interested? Contact me ASAP! It's too good to pass up.",
    u"Who hasn't got their student loan yet? We want to hear from you",
    u'Just got a cheque for \xa3500... Nice. #scholarship #win :D',
    u'WHERE IS MY STUDENT LOAN?!',
    u'#DMCRSS Student loan debt hits record 1 in 5 US households: Student loan debt has reached a record 1 in 5 ... http://t.co/bE6EuhRX #NEWS',
    u'Student Loan Debt at Record Numbers: Pew Research Analysis http://t.co/tYGqSeRs /Want to see housing market take off? Forgive student loans.',
    u'Hajj by a Student Loan: Permissible? http://t.co/1KrziaBz #sufi',
    u'STUDENT LOAN WHERE ARE YOU??',
    u'back to college till 6.30 omg -.-  http://t.co/JEq6SQWC',
    u'How to make the most of your college tours: http://t.co/BKXHH1ft',
    u'This girl on this college tour is wearing 5 in red pumps',
    u"@ohhelloellie What's up Ellll? Come back to college please :(",
    u'Need Money For School??? Scholarships are Available!!!\n\n2012-2013 Xerox Technical Minority Scholarship... http://t.co/ndbxzzQ0',
    u'Have You Done Your FAFSA? - #education #students http://t.co/67fLcuiz',
    u'Ever Have a Student Loan? Learn How You Can Benefit! http://t.co/CZ4VKbhc',
    u'Does anyone know when I will get my student loan? Warwick University...',
    u'@TiffSkins oh my oh my. Get that with ya student loan did ya? \U0001f61b',
    u'has anyone elses student loan not come through ?',
    u'Not received your student loan? Have signed &amp; returned your declaration form?',
    u'Not received your student loan? Have you signed &amp; returned your declaration form?',
    u'Did anyone get their student loan through?',
    u'Dear Student Loan, please live in my bank?  I promise to  take you out every so often, to topshop, asda and toysrus. Thaaanks!',
    u'Hispanic? CUNY student? 3.0 gpa or higher? Need $ for college? Scholarship Opportunity! #hispanicscholarship #CUNY http://t.co/16VfYYYE',
    u"Our guides rock! RT @micmic2013 The best college tour I've ever been on! #sofun @photographyduz @RosemontCollege http://t.co/Eux22Ivm",
    u"If you're in need of a scholarship, I've got one for ya here: http://t.co/GfiOMhMu - sp",
    u'In #College?  Do you #volunteer on campus or in community?  Enter @NatlStudentDay contest-opp to win #scholarship: http://t.co/QkaMvQIb',
    u"So excited that my @herkulesworld is here all the way from DC.  He's the host of the BET College Tour!  http://t.co/gsu7eKH3",
    u'World Learning Merit- And Need-Based Scholarships http://t.co/94lkRhsu',
    u'@BarackObama  I got a great education in the USA now $100,000 in PRIVATE student loan debt. When will u address private loan problem?',
    u"Can't wait for college and to get away from here",
    u'OH YEAH SHE GOT INTO COLLEGE. Omg this movie is so awkward without her',
    u'If you pay back \xa330 a month,, in 50 years years you will have only paid back 2 thirds of the Student loan...Fail? #bbcqt',
    u'Hate these days. (I wanna back to college, please).',
    u'Just spent $75 for the Phi Theta Kappa membership at SanJac. It better get me some scholarships.',
    u'Trying to work out how much I pay back in Student Loan payments per month under the old system. Answer? Too much.',
    u"How did yo stupid ass get into college again? Must've been a track scholarship -__-",
    u'Anyone want to give me \xa31000 so i can get a flight to see the missus? No? Fuck. Guess i need to win this scholarship...',
    u'rumah ade student loan ke? hahaha ..',
    u'Cant wait to get my scholarship ! #moneymoney',
    u'When i was offered that scholarship i was so excited.....but quickly it was taken. Thank you public school politics.',
    u'Hope everyone had a great first day of classes! Remember, scholarship comes first!',
    u'IM NOT IGNORING YOU . IM JUST TRYNNA DO MY SCHOLARSHIP SHIT . AGH . STOP TALKING TO ME .',
    u'Home! okay ive one hour to rest. Gotta go back to college at 1 plus.',
    u"No don try to fucking play me like I'm stupid. You clearly have me fucked up. Wait until I find me another scholarship...Fuck outta here!",
    u'Why do I need to feel bad for people with large student loan debts? No one paid for my college &amp; I turned out just fine. Oh...wait...',
    u"Is it the Friday before Easter? Because I've just got my wages and student loan through. Certainly feels like a Good Friday.",
    u'@ChloeWalton1 when does student loan go innnn? I am POOR :( and I seem to always ask you my student money worries... #fountainofknowledge ;)',
    u'@EliotCatterson take it the student loan been blasted on booze??',
    u'Work paid me, student loan, student grant in all on the same day. Shopping spree, amirite?',
    u'@amylea_94 have you heard anything about your student loan yet?',
    u'Debating to set some student loan aside for a new wardrobe? #probsnotwise #donttellthemother',
    u"Discount on PTPTN student loan holders? Hmmm, not so sure about that. It's good, but the conditions could open up loopholes.",
    u"@treehouse Thanks so much for the scholarship! Already started earning badges!! Can't wait to learn more!",
    u'does anyone have their student loan yet?',
    u'@Jordeo student loan? I have \xa3178 :| oops',
    u'Why does everyone have their student loan apart from me :(',
    u'FIFA 13 thanks to my student loan. Who needs food anyway?',
    u'WHERE IS MY STUDENT LOAN?',
    u'Why hasnt my student loan come in? #worried',
    u'Double staff discount in Tesco this weekend? There goes my student loan....and wages',
    u'@sarah_mowatt what? of course i am...ive got my student loan :P',
    u'student loan where are you?!',
    u'Has anybody elses student loan not come yet?',
    u'Full schedule of classes and the Private Lesson Marathon. Busy couple of days. Are your lessons scheduled yet?  Great cause..SCHOLARSHIPS!',
    u'My student loan has dropped who wants me to buy them FIFA 13?',
    u"Student Loan comes through... what's the first thing I order? Football Manager 2013! #Standard",
    u'Any danger of my student loan coming in? #poor #hungry #cold',
    u'@admoxly i doubt they would like! No not yet, havent even started college yet so no student loan! U or ur bro gonna sell me yours yet?',
    u"Can't wait for college to be over!! #longday #weekend",
    u"@EcstasyKills my fafsa never came threw so I'm fucked",
    u"@TashaFranek to buy some nail polish. still no student loan :( you? i'm going valve now btw, just not drinking",
    u'Black college tour on campus!! I love my Hbu!!! #BETCollegeTour',
    u"@trestinyhays Isn't that all you live on usually though? Even with the student loan??",
    u'where for art thou student loan?',
    u'Is it a common sight in Dennistoun to see the locals bin raid? Might need to take it up if ma student loan doesn"t come through soon #classy',
    u'BET Black College Tour today!!! I love my HBCU! This weekend is gonna be FANTABULOUS.',
    u'@kissedby_KAY aww cuz imma leave for a college visit soon haha wbu',
    u'@dani_emma_p good excuse to go camera shopping? Student loan? ;) x',
    u'BET Black College Tour is at CAU!',
    u'Not smart to get scholarship. Not positive in life. Fuck it and die. Save it all for ur smart son. He can pay back every cent and more.',
    u'-So the BET Black college tour is at my school...',
    u"BET Black College Tour At CAU Todayy. :) Turn Up CAU. I Won't Be In That Crowd!",
    u'Mmmm, pay day + student loan = shoes? Handbags? Clothes? Nope, bloody books. BOO!',
    u"@MariaBooth0420 I'm hoping to get a scholarship to college. Since I'm still in high school and applying to college now",
    u'@_BeatMyTweets_ @ll_heartthrob all them scholarships you got you good',
    u'@the_nowheregirl ahora lo vi. Wtf? Eso es en serio? De qu\xe9 es eso? Fafsa?',
    u'At the BET college tour',
    u'BET College Tour at CAU',
    u'I just played DONT SLEEP @the bet college tour, I was snoring. #betdontsleep',
    u"I can tell my student loan isn't gonna last long #shopping",
    u"@Seventeenmodels what's up? i haven't received my student loan which i need in order to live / was meant to receive on monday.....",
    u"@leximaex i think there's an essay too\u2026like a dodge college application thingy and the chapman supplement essay sahkjfh",
    u'BET College Tour is at Clark today!',
    u"I am inspired by Zakiya Adair's brilliant scholarship on black women vaudeville performers in a transatlantic context. #ASALH",
    u"@naRszerrooniey mm... nunggu have much money or get scholarship. In m'sia ada vet med?",
    u"@tstafford316 no you don't. To get into a 4 year college you need to foreign languages. To graduate high school you don't need to.",
    u"Ain't nothin' like waking up on a Friday to a phone call from the federal student loan office demanding to know where your payment is.",
    u'Out of work at 2..then seeing grandma. Going to bank to pay car loan. Then pay student loan. Then bowling later tonight..Staying busy.',
    u'Seems dead weird to be going back to college at this time even though this time yday i hadnt started my last lesson!',
    u'I get to volunteer with kittens at the animal shelter...yay! And it goes on my college application &gt;&gt;&gt;&gt;&gt;&gt;',
    u'Woo student loan! No longer in a relationship with my overdraft #somuchmoney',
    u'Check out the BET College Tour outside the student center! They will be here all day! No class cutting! Education first!',
    u'Tax is bloody annoying. As is pension, student loan and generally the fact that someone else gets the pennies!',
    u'BET at my school for Black College Tour!!',
    u'At black college tour #BETDONTSLEEP',
    u'BET College tour need to come by State... Hell we an HBCU on the low too lol',
    u'BET Black College Tour at my school #CAU',
    u'Where is my student loan please?',
    u'BET college tour at CAU. Atlanta gone be stupid pack !',
    u"Ok I'm gonna have a world record for spending my student loan the fast about \xa31200 of it is spoken for....",
    u"@EhsanKamilRadzi about 20+ IPTAs in m'sia. how gvmt can support students scholarship? Duit PT skrg pon diguna buat kerja lagha.",
    u"Bet you won't mob Clark lol RT @FloridaMarlon23: The got the BET Black College Tour on Clark Atlanta campus",
    u'My student loan is defs going to be gone on clothes',
    u'At the BET college tour',
    u"BET College Tour \U0001f601 Gotta Love HBCU's",
    u'Mr. Debonair Scholarship Pageant Wednesday, 10/3/12. MSC Auditorium 7:08 pm. Admission: One Canned Good. #ZetaGammaAKA',
    u'I should want these boys to do well on there scholarship testing, but all I really want is for them to hurry up and be done so I can eat...',
    u'Yess RT @_MrEverythinggg: Now ? RT @Papi_NO_Mas: BET Black College Tour at my school #CAU',
    u'Thanks everyone who bought a ticket to the game on Sunday... come support Chris Brown and #Hittsquad #BET #COLLEGE TOUR',
    u'BET black college tour is overrated.',
    u'WHERE THE FUCK IS MY STUDENT LOAN I NEED FOOD',
    u'bet college tour at clark. i might have to show my face',
    u'Got your student loan? Come and give it to us! New promos running tonight! \xa33 jam jars, \xa32 oranjeboom and \xa32 coors. All washed down with CC',
    u'BET COLLEGE TOUR HERE AT MY SCHOOL AND YEAH !!! #BETDONTSLEEP CAN YOU DIG IT?',
    u'Out here at this BET college tour #betdontsleep !',
    u'do I wanna go to the little BET College Tour',
    u'#ReasonsForCollegiateBeerPong so @PartyKidzz can come back to college as an athlete',
    u"@SeyariaGotSwag idk. I'm not leaving till like 5 or 6. He's at a college visit",
    u"I'm annoyed. Stop talking. Your making me go to the fucking sub. Don't talk to me about scholarships.",
    u'Can I just have my student loan now please?',
    u'Shit is the new Fifa out? Where the foook is my student loan already?',
    u'It laughable how stupid some people are. Makes me wonder how they got into college.',
    u'Wat leuk! Janine Jansen op #Ned3 bij College Tour.',
    u'We out here at the BET College Tour. #ATL',
    u'So I have my student loan ... And I never knew \U0001f64a',
    u'Nova College Tour met Janine Janssen als gast aan het kijken. Een van de beste programma\u2019s op de Nederlandse tv.',
    u'Not even gonna use this student loan',
    u'College Tour met top violiste Janine Jansen #NTR #collegetour #genieten #inspirerend',
    u'What if you looked up one day &amp; it was a tour called "The \u20achiefy Tribe College Tour" .... #randomthought',
    u"Just a reminder:  If you'll be starting KSU in the Spring of 2013, make sure you've completed the 2012-2013 FAFSA.  The priority filing...",
    u"On the way to turn up at BET Black College tour on Clark Campus with @ChloeMondesir ! We'll be the ones in the Spelman shirts too turnt. Lol",
    u'Student loan is finally in! Never felt so rich #wontlast',
    u'I gotta get to the black college tour!',
    u"Am I the only one who hasn't got their student loan yet? I have uni rent to pay \U0001f620",
    u"I Gotta Call EKU Back. I'm Suppose To Transfer There Next Year #Hoop. Damn I Love Scholarships !",
    u'wow wat een wijsheid en prachtige vrouw ... janine jansen #college tour',
    u'Janine jansen bij college tour op Nederland drie ,wat leuke meid he, en dan ook nog zo mooi viool spelen !',
    u'"i don\'t get college scholarships for being white" "where is white history month" "why can\'t i have white pride"',
    u"I don't have a 7th period will I have student aid but that doesn't count! :p",
    u"\u201c@TeaPartyExpress: College tuition on Obama's inauguration day averaged $6,591. Today it averages $8,244. #Obamaisntworking #youth\u201d",
    u"I wish Chichester College didn't fuck up my student loan. I have so many online shopping baskets ready for checkout!",
    u'if napping was a college major i could pass doctorate level classes',
    u'I want my fafsa money.',
    u'Zeker! RT @Malgosiafiebig: Prachtig interview met Janine Jansen at NTR College Tour!',
    u'Ithaca College in New York offers Merit-based scholarship of $7,000 to $18,000 per year. Admission@ithaca.edu',
    u'@eddieshi1 My "MR. PERFECT" "Bet YOUR KIDS College Tuition Pick of the Week": Louisiana Tech -3 @ UVA. You\'re Welcome! Thank Me Tomorrow.',
    u'\u201c@Sarah_Vanhorn12: When @mollz_bollz ask me how I got into college &lt;&lt;&lt; \U0001f635\U0001f52b\u201d hahahahahahaha who ate tanning lotion today?!',
    u'Wish my student loan would hurry up and get in my bank! #shopsarecallingme #cannotwait #retailtherapy',
    u'Hurry up student loan, im dyingggg.',
    u"Yep so I can't wait to go back to college wednesday and tell alison what I think of her!! #BITCH :@",
    u"Interested in enrolling in @NutritionSchool ? I have a $2k scholarship to give away! Comment if you're interested. #education #nutrition",
    u'I am so tired of all of this college and scholarship crap....#annoying',
    u'Going to a cash machine to check your balance then realising your student loan has went in. Tears of happiness where flowing',
    u"Why's my student loan taking forevs? Desp to shop",
    u'All them girls that got all dressed up for the BET Black College Tour just got they ass rained on lol',
    u'fresh batch of AM1s in work today, keep eyeing up shoes, want my student loan!',
    u'lol wrrdd?  RT @i_breatheBeauty: - BET College tour is so corny , they try to make it look live on tv though !',
    u'Took a long walk from home st. To wall st. I under estimated the distance from my house and the student aid building... #Exhausted.',
    u'@lauramcollett do it! We miss you and @stroud14 coming in. Hope you are enjoying uni life and drinking away your student loan!! Xx',
    u"She my little dancer, she don't need a fafsa. Brain so good, messed around and got a bachelor",
    u"And I'm ready to go back to college now...my mom is bat shit crazy",
    u'Student loan hurry the fuck up. There are so many things that I want to buy!',
    u'Has anyone got their student loan or grant yet??',
    u'The BET College Tour was fun though. I got 4 t-shirts.',
    u'Bet college tour &gt;&gt;&gt; #cau',
    u"Apparently you get a scholarship if you're left handed as well.",
    u'So has anyone seen the college tour commercial ?!? ... #umes #betcollegetour',
    u"Snoop Dogg's son is giving up his football scholarship to become a rapper? Wow.",
    u'WHERE IS MY STUDENT LOAN?!',
    u'Loving life!!! xD #slightlydrunk or #bipolar? Or maybe just because my student loan went in!',
    u'How much of your student loan is okay to spend on clothes?',
    u'no this is a joke now. where is my student loan?',
    u'would a student loan go through on a Saturday?',
    u'Make sure you #SaveTheDate for The #LoveMikeNia 3rd Annual Scholarship Fundraiser sponsored by @Stoli Vodka and Pretty Girlz Inc. 11/15/12!!',
    u"Screw trying to switch my college major. I'd rather just get into porn.",
    u"\u201c@AndrewHeads: Student loan has just came through when I'm at the casino #dangerous\u201d all on red! #dareya",
    u'Current and future alumni make sure you read your student loan exit counseling papers closely. You could be eligible for loan forgiveness.',
    u"Had a very successful shopping trip with my student loan! \U0001f601 It's good to be homeeeeeee\U0001f49c",
    u"I looked to see if I wiukd change but I wiukd have meant going back to the start and I didn't want to miss out. \xa3500 student loan came handy"
    ]
